/**
 * Error payload returned by all API endpoints on failure.
 */
export type ErrorResponse<S extends number> = {
    /**
     * HTTP status code generated by the origin server for the failure.
     */
    status: S

    /**
     * Human-readable message summarizing the cause of the failure.
     */
    message: string

    /**
     * Additional error details.
     */
    details?: { [key: string]: any }
}