name: preview
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
on:
  push:
    branches-ignore:
      - dev
      - main
jobs:
  deploy:
    environment: development
    runs-on: hatsuboshi
    steps:
      - uses: actions/checkout@v7
      - name: setup environment variables
        run: |
          touch .env
          echo API_ENV=production >> .env
          echo PORT=3001 >> .env
          echo MONGO_SHARED="${{ secrets.MONGO_SHARED }}" >> .env
          echo MONGO_CLUSTER="${{ secrets.MONGO_CLUSTER }}" >> .env
          echo MONGO_USER="${{ secrets.MONGO_USER }}" >> .env
          echo MONGO_PASS="${{ secrets.MONGO_PASS }}" >> .env
          echo S3_KEY="${{ secrets.S3_KEY }}" >> .env
          echo S3_SECRET="${{ secrets.S3_SECRET }}" >> .env
          echo S3_REGION="${{ secrets.S3_REGION }}" >> .env
          echo S3_BUCKET="${{ secrets.S3_BUCKET }}" >> .env
      - name: install vercel cli
        run: |
          npm install --global vercel@latest
      - name: build & deploy
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}